name: Continuous integration (CI) Java

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  IntegracaoDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build
      - name: Build project
        run: mvn clean install

      # Teste de Unidade
      - name: Teste de Unidade
        run: mvn test

      # Teste de Integração
      #- name: Testes de Integração
      #  run: mvn verify
