name: Continuous integration (CI)

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias a meia noite
  push:
    branches:
      - feature/LOC-69
  pull_request:
    branches:
      - dev

jobs:
  IntegracaoDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install

     #Teste de Integração e Unidade
      - name: Testes
        run: mvn verify






