name: Continuous integration (CI)

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias a meia noite
  push:
    branches:
      - feature/LOC-69

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install -DskipTests


      # Check if the test folder exists before running tests
      - name: Check if test folder exists
        run: |
          if [ -d "src/test/java" ]; then
            echo "Test folder exists. Running unit tests.";
           # mvn test  # Execute tests only if the folder exists
          else
            echo "Test folder does not exist. Skipping unit tests.";
          fi

      # Upload Unit Test Results (only if tests were run and reports exist)
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: target/surefire-reports

      #Chama o Deploy



