name: Continuous integration (CI)

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias a meia noite
  push:
    branches:
      - feature/LOC-69

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install -DskipTests
          
          
          # Check if test folder exists before running tests
               - name: Check if test folder exists and run verify
               run: |
                 if [ -d "src/test/java" ]; then
                 echo "Test folder exists. Running mvn verify with tests.";
                 mvn --batch-mode --update-snapshots verify
                 else
                 echo "Test folder does not exist. Skipping verify step with tests.";
                 fi
                 
                 # Upload Unit Test Results if they exist
                 - name: Upload Unit Test Results
                   if: ${{ always() && (steps.check-test-folder.outputs.folder_exists == 'true') }}
                   uses: actions/upload-artifact@v3
                   with:
                     name: unit-tests-results
                     path: target/surefire-reports



