name: Continuous integration (CI)

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias a meia noite
  push:
    branches:
      - feature/LOC-69

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install -DskipTests


      # Run unit tests
      - name: Run Unit Tests
        run: mvn test

      # Check if test reports exist and handle accordingly
      - name: Check if test reports exist
        run: |
          if [ -d "target/surefire-reports" ]; then
            echo "Test reports found, proceeding with the next steps.";
          else
            echo "No test reports found, skipping the upload.";
            exit 0; # Skip the next step (upload) if no reports
          fi

      # Upload Unit Test Results (if the reports exist)
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: target/surefire-reports
      #Chama o Deploy



