name: Continuous integration (CI)

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias a meia noite
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install -DskipTests



      #Chama o Deploy



