name: Continuous integration (CI)

on:

  push:
    branches:
      - feature/LOC-69
  schedule:
  - cron: '0 0 * * *' # Executa todos os dias a meia noite
  #- cron: '*/6 * * * *' # Executa a cada 6 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Build
      - name: Build project
        run: mvn clean install

        # Executa testes de Unidade
      - name: Test unit
        run: mvn test

      # Executa testes de integração
      - name: Test Integration
        run: mvn verify








