name: Deploy

on:
  push:
    branches:
      - feature/LOC-72

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ vars.GIT_REPOSITORY_BACKEND }}/${{ vars.DOCKER_IMAGE_BACKEND }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ vars.GIT_REPOSITORY_BACKEND }}/${{ vars.DOCKER_IMAGE_BACKEND }}:latest

  deploy:
    needs: build
    runs-on: backend
    steps:
      - name: Remove Docker container
        run: docker rm -f ${{ secrets.DOCKER_CONTAINER_BACKEND }}

      - name: Remove unused Docker images
        run: docker image prune -a -f

      - name: Run Docker container
        run: docker run -d --name ${{ secrets.DOCKER_CONTAINER_BACKEND }} --network ${{ secrets.DOCKER_NETWORK }} -p 9090:9090 -e DOCKER_DATABASE_CONTAINER=${{ secrets.DOCKER_CONTAINER_DATABASE }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' ghcr.io/${{ vars.GIT_REPOSITORY_BACKEND }}/${{ vars.DOCKER_IMAGE_BACKEND }}:latest
