name: Teste de Unidades (CI) Java

on:
  push:
    branches-ignore: # Ignora pushes nas branches main e dev
      - main
      - dev

jobs:
  testeDeUnidade:
    if: >
      startsWith(github.event.head_commit.message, 'feature') ||
      startsWith(github.event.head_commit.message, 'fix') ||
      startsWith(github.event.head_commit.message, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build
      - name: Build project
        run: mvn clean

      # Teste de Unidade
      - name: Teste de Unidade
        run: mvn test
